platform :ios, '7.0'

target :StandardizationPractice do
    pod 'HTToast' , :git=>'https://g.hz.netease.com/HTIOSUI/HTToast.git'
    pod 'HTBadgeTextView' , :git=>'https://g.hz.netease.com/HTIOSUI/HTBadgeTextView.git'
    pod 'UniversalRouter' , :git=>'https://g.hz.netease.com/HTIOSUI/UniversalRouter.git'
    pod 'HTR3' , :git=>'https://g.hz.netease.com/HeartTouchOpen/HTR3.git'
    pod 'HTPageControllerView' , :git=>'https://g.hz.netease.com/HTIOSUI/HTPageControllerView.git'
    pod 'HTImageView' , :git=>'https://g.hz.netease.com/HTIOSUI/HTImageView.git'
    pod 'HTRefreshView' , :git=>'https://g.hz.netease.com/HTIOSUI/HTRefreshView.git'
    pod 'HTCommonUtility', :git => 'https://g.hz.netease.com/HeartTouchOpen/HTCommonUtils.git', :branch => 'poct'
    pod 'HTNetworking', :git => 'https://g.hz.netease.com/HeartTouchOpen/HTNetworking.git'
    pod 'HTSegmentView', :git => 'https://g.hz.netease.com/HTIOSUI/HTSegmentView.git'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
    pod 'BlocksKit' ,  '~>2.2.5'
    pod 'IQKeyboardManager' , '~>3.3.7'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'CocoaLumberjack', '~> 2.3.0'
    pod 'MGSwipeTableCell', '1.5.1'
    pod 'Masonry'
pod 'HTAssetsPicker' , :git=>'https://g.hz.netease.com/HTIOSUI/HTAssetsPicker.git'

end

